server:
  port: 8080
javax:
  sql:
    DataSource:
      airportDataSource:
        dataSourceClassName: com.mysql.cj.jdbc.MysqlDataSource
        dataSource:
          url: jdbc:mysql://localhost:3306/helidon_ums
          user: root
          password: 6498
